### ISSUE TITLE
 `admin_metadata_uri': undefined method `value'

### ISSUE THREAD

**Issue by jimfhahn** [sul-dlss-labs/rdf2marc#2]
Hi, I really like this model matching approach, and I think this will be a great way to convert.
I've been using this code to evaluate some records at Penn. One thing I wasn't sure about is how admin metadata is expected for the most recent update. If I take an instance URI from UPenn in Sinopia stage  ( https://trellis.stage.sinopia.io/repository/penn/d6b74251-1532-477d-942c-92802c7cb2ba
 ),

bash-3.2$ exe/rdf2model https://trellis.stage.sinopia.io/repository/penn/d6b74251-1532-477d-942c-92802c7cb2ba

I am finding this error:

Traceback (most recent call last):
        1: from exe/rdf2model:16:in `<main>'
/Users/jimhahn/rdf2marc/lib/rdf2marc/graph_helper.rb:41:in `admin_metadata_uri': undefined method `value' for #<RDF::Node:0x00007ff2e936c228> (NoMethodError)

Is there a certain minimal admin metadata that is expected?

Thanks,
Jim

**Comment by justinlittman** [comment]
There was a recent change to the resource templates that switched Admin metadata to be a referenced resource rather than a nested resource; you need to change this record so that it references an Admin metadata resource.

Let me know if that helps or you encounter other problems.

**Comment by jimfhahn** [comment]
That worked for me, thanks!
