### ISSUE TITLE
id.loc.gov authorities moved to https://

### ISSUE THREAD

**Issue by jimfhahn** [sul-dlss-labs/rdf2marc#5]
Great project! I was revisiting this work today and noticed that Sinopia records that have /id.loc.gov name authorities that do not begin with https:// will not convert. This potentially impacts many legacy Sinopia records where it seems that Sinopia defaulted to http://

**Comment by justinlittman** [comment]
Thanks for reporting @jimfhahn. This should now be fixed. Can you verify?

**Comment by jimfhahn** [comment]
@justinlittman working as expected now, thank you!
